// Git hook install/uninstall/status.
//
// Default mode: pre-commit — installs a shell block that rebuilds the graph
// BEFORE the commit and auto-stages the output artifacts so they land in the
// same commit. Optional --mode=post-commit restores the old behavior.
//
// Idempotent: re-running install replaces the block. If a hook already exists
// from another tool, our block is appended without disturbing it.
// Switching modes: the marker is stripped from the old file and written to the new.

import { existsSync } from 'node:fs';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { appendBlock, replaceMarkedSection, stripMarkedSection } from './marker-block.js';
import { registerProject } from './project-registry.js';

export const MARK_START = '# >>> arch-graph >>>';
export const MARK_END = '# <<< arch-graph <<<';

export function preCommitHookPath(repo: string): string {
    return resolve(repo, '.git', 'hooks', 'pre-commit');
}

export function postCommitHookPath(repo: string): string {
    return resolve(repo, '.git', 'hooks', 'post-commit');
}

// ---------------------------------------------------------------------------
// Hook body templates
// ---------------------------------------------------------------------------

const PRE_COMMIT_BODY = `${MARK_START}
# Auto-rebuild arch-graph before commits that touch TypeScript files.
# Managed by \`arch-graph hook install\` — edit between markers will be overwritten.
if command -v arch-graph >/dev/null 2>&1; then
    if git diff --cached --name-only --diff-filter=ACMR 2>/dev/null | grep -qE '\\.ts$'; then
        # Real build errors (config parse, I/O) block the commit. Recall-floor
        # regressions are advisory by default and do not block — see \`arch-graph
        # build --strict\` for CI gating.
        arch-graph build --quiet || exit 1
        # Stage the graph + diagnostics + validation outputs so they go into this commit.
        # graph.mermaid stays — it's a viewable artifact; mermaid-collisions.json too.
        # If arch-graph-out/ is in .gitignore the \`git add -f\` is required, but the
        # install step warns the user — see init flow.
        git add arch-graph-out/graph.json \\
                arch-graph-out/diagnostics.json \\
                arch-graph-out/validation.json \\
                arch-graph-out/graph.mermaid 2>/dev/null || true
    fi
fi
${MARK_END}
`;

const POST_COMMIT_BODY = `${MARK_START}
# Auto-rebuild arch-graph after commits that touch TypeScript files.
# Generated by \`arch-graph hook install --mode=post-commit\` — edit between markers will be
# overwritten on the next install. Remove with \`arch-graph hook uninstall\`.
if command -v arch-graph >/dev/null 2>&1; then
    # \`git diff-tree -r --no-commit-id --name-only HEAD\` works on the initial
    # commit too (HEAD~1 would not), and prints one path per line.
    if git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | grep -qE '\\.ts$'; then
        arch-graph build --quiet || true
    fi
fi
${MARK_END}
`;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type HookMode = 'pre-commit' | 'post-commit';

export interface HookArgs {
    repo: string; // path to repo root (we resolve .git/hooks/<hook> under it)
    mode: HookMode;
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export function parseHookArgs(argv: string[]): { sub: string; args: HookArgs } {
    const [sub, ...rest] = argv;
    let repo = '.';
    let mode: HookMode = 'pre-commit';

    for (let i = 0; i < rest.length; i++) {
        const a = rest[i]!;
        if (a === '--repo' && rest[i + 1]) {
            repo = rest[++i]!;
        } else if (a.startsWith('--repo=')) {
            repo = a.slice('--repo='.length);
        } else if (a === '--mode' && rest[i + 1]) {
            mode = validateMode(rest[++i]!);
        } else if (a.startsWith('--mode=')) {
            mode = validateMode(a.slice('--mode='.length));
        }
    }
    return { sub: sub ?? '', args: { repo: resolve(repo), mode } };
}

function validateMode(raw: string): HookMode {
    if (raw === 'pre-commit' || raw === 'post-commit') return raw;
    process.stderr.write(`error: --mode must be "pre-commit" or "post-commit", got "${raw}"\n`);
    process.exit(2);
}

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

async function ensureGitRepo(repo: string): Promise<void> {
    if (!existsSync(resolve(repo, '.git'))) {
        throw new Error(`not a git repository: ${repo} (no .git directory)`);
    }
}

/**
 * Remove the arch-graph marker block from `filePath` if present.
 * Deletes the file if it becomes meaningless (shebang + comments only).
 */
async function removeMarkerFromFile(filePath: string): Promise<void> {
    if (!existsSync(filePath)) return;
    const body = await readFile(filePath, 'utf8');
    if (!body.includes(MARK_START)) return;

    const stripped = stripMarkedSection(body, MARK_START, MARK_END);
    const meaningful = stripped
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l.length > 0 && !l.startsWith('#'))
        .join('');
    if (meaningful.length === 0) {
        const { unlink } = await import('node:fs/promises');
        await unlink(filePath);
    } else {
        await writeFile(filePath, stripped, 'utf8');
    }
}

/**
 * Write a hook block to `filePath`, replacing an existing arch-graph block
 * or appending to an existing third-party hook, or creating a fresh file.
 */
async function writeHookBlock(filePath: string, hookName: string, body: string): Promise<void> {
    await mkdir(dirname(filePath), { recursive: true });

    let existing = '';
    if (existsSync(filePath)) {
        existing = await readFile(filePath, 'utf8');
    }

    let next: string;
    if (existing.includes(MARK_START) && existing.includes(MARK_END)) {
        // Idempotent re-install: rewrite the block in place.
        next = replaceMarkedSection(existing, MARK_START, MARK_END, body);
    } else if (existing.length === 0) {
        next = `#!/bin/sh\n# git ${hookName} hook — managed by arch-graph (and possibly others)\n\n${body}`;
    } else {
        // Pre-existing hook from another tool — preserve it, append our block.
        next = appendBlock(existing, body);
        // Make sure the file still starts with a shebang.
        if (!next.startsWith('#!')) next = `#!/bin/sh\n${next}`;
    }

    await writeFile(filePath, next, 'utf8');
    await chmod(filePath, 0o755);
}

// ---------------------------------------------------------------------------
// Public commands
// ---------------------------------------------------------------------------

export async function hookInstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    await registerProject(args.repo);

    if (args.mode === 'pre-commit') {
        const target = preCommitHookPath(args.repo);
        const other = postCommitHookPath(args.repo);
        // Strip marker from the old mode's file when switching.
        await removeMarkerFromFile(other);
        await writeHookBlock(target, 'pre-commit', PRE_COMMIT_BODY);
        process.stdout.write(`✓ pre-commit hook installed at ${target}\n`);
        process.stdout.write(`  Rebuilds graph + stages artifacts before commits touching .ts files.\n`);
        process.stdout.write(`  Remove with: arch-graph hook uninstall\n`);
    } else {
        const target = postCommitHookPath(args.repo);
        const other = preCommitHookPath(args.repo);
        // Strip marker from the old mode's file when switching.
        await removeMarkerFromFile(other);
        await writeHookBlock(target, 'post-commit', POST_COMMIT_BODY);
        process.stdout.write(`✓ post-commit hook installed at ${target}\n`);
        process.stdout.write(`  Triggers \`arch-graph build --quiet\` after commits touching .ts files.\n`);
        process.stdout.write(`  Remove with: arch-graph hook uninstall\n`);
    }
}

export async function hookUninstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const pre = preCommitHookPath(args.repo);
    const post = postCommitHookPath(args.repo);

    let removed = 0;

    for (const [label, p] of [['pre-commit', pre], ['post-commit', post]] as [string, string][]) {
        if (!existsSync(p)) continue;
        const body = await readFile(p, 'utf8');
        if (!body.includes(MARK_START)) continue;

        const stripped = stripMarkedSection(body, MARK_START, MARK_END);
        const meaningful = stripped
            .split('\n')
            .map((l) => l.trim())
            .filter((l) => l.length > 0 && !l.startsWith('#'))
            .join('');
        if (meaningful.length === 0) {
            const { unlink } = await import('node:fs/promises');
            await unlink(p);
            process.stdout.write(`✓ removed empty ${label} hook ${p}\n`);
        } else {
            await writeFile(p, stripped, 'utf8');
            process.stdout.write(`✓ removed arch-graph block from ${p}\n`);
        }
        removed++;
    }

    if (removed === 0) {
        process.stdout.write(`(no arch-graph block found in pre-commit or post-commit hooks)\n`);
    }
}

export async function hookStatus(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const pre = preCommitHookPath(args.repo);
    const post = postCommitHookPath(args.repo);

    let found = false;

    if (existsSync(pre)) {
        const body = await readFile(pre, 'utf8');
        if (body.includes(MARK_START)) {
            const lines = body.split('\n').length;
            process.stdout.write(`status: installed (mode=pre-commit) at ${pre} (${lines} lines total)\n`);
            found = true;
        }
    }

    if (existsSync(post)) {
        const body = await readFile(post, 'utf8');
        if (body.includes(MARK_START)) {
            const lines = body.split('\n').length;
            process.stdout.write(`status: installed (mode=post-commit) at ${post} (${lines} lines total)\n`);
            found = true;
        }
    }

    if (!found) {
        process.stdout.write(`status: not installed (no arch-graph block in pre-commit or post-commit hooks)\n`);
    }
}
