// Git post-commit hook install/uninstall/status.
//
// Installs a small shell block — delimited by markers — that re-runs
// `arch-graph build --quiet` after every commit that touched a .ts file.
// Idempotent: re-running install replaces the block. If a hook already exists
// from another tool, our block is appended without disturbing it.

import { existsSync } from 'node:fs';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { appendBlock, replaceMarkedSection, stripMarkedSection } from './claude.js';

const MARK_START = '# >>> arch-graph >>>';
const MARK_END = '# <<< arch-graph <<<';

const HOOK_BODY = `${MARK_START}
# Auto-rebuild arch-graph after commits that touch TypeScript files.
# Generated by \`arch-graph hook install\` — edit between markers will be
# overwritten on the next install. Remove with \`arch-graph hook uninstall\`.
if command -v arch-graph >/dev/null 2>&1; then
    # \`git diff-tree -r --no-commit-id --name-only HEAD\` works on the initial
    # commit too (HEAD~1 would not), and prints one path per line.
    if git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | grep -qE '\\.ts$'; then
        arch-graph build --quiet || true
    fi
fi
${MARK_END}
`;

interface HookArgs {
    repo: string; // path to repo root (we resolve .git/hooks/post-commit under it)
}

export function parseHookArgs(argv: string[]): { sub: string; args: HookArgs } {
    const [sub, ...rest] = argv;
    let repo = '.';
    for (let i = 0; i < rest.length; i++) {
        const a = rest[i]!;
        if (a === '--repo' && rest[i + 1]) {
            repo = rest[++i]!;
        } else if (a.startsWith('--repo=')) {
            repo = a.slice('--repo='.length);
        }
    }
    return { sub: sub ?? '', args: { repo: resolve(repo) } };
}

function hookPath(repo: string): string {
    return resolve(repo, '.git', 'hooks', 'post-commit');
}

async function ensureGitRepo(repo: string): Promise<void> {
    if (!existsSync(resolve(repo, '.git'))) {
        throw new Error(`not a git repository: ${repo} (no .git directory)`);
    }
}

export async function hookInstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const p = hookPath(args.repo);
    await mkdir(dirname(p), { recursive: true });

    let existing = '';
    if (existsSync(p)) {
        existing = await readFile(p, 'utf8');
    }

    let next: string;
    if (existing.includes(MARK_START) && existing.includes(MARK_END)) {
        // Idempotent re-install: rewrite the block in place.
        next = replaceMarkedSection(existing, MARK_START, MARK_END, HOOK_BODY);
    } else if (existing.length === 0) {
        next = `#!/bin/sh\n# git post-commit hook — managed by arch-graph (and possibly others)\n\n${HOOK_BODY}`;
    } else {
        // Pre-existing hook from another tool — preserve it, append our block.
        next = appendBlock(existing, HOOK_BODY);
        // Make sure the file still starts with a shebang.
        if (!next.startsWith('#!')) next = `#!/bin/sh\n${next}`;
    }

    await writeFile(p, next, 'utf8');
    await chmod(p, 0o755);
    process.stdout.write(`✓ post-commit hook installed at ${p}\n`);
    process.stdout.write(`  Triggers \`arch-graph build --quiet\` on any commit touching .ts files.\n`);
    process.stdout.write(`  Remove with: arch-graph hook uninstall\n`);
}

export async function hookUninstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const p = hookPath(args.repo);
    if (!existsSync(p)) {
        process.stdout.write(`(no post-commit hook at ${p})\n`);
        return;
    }
    const existing = await readFile(p, 'utf8');
    if (!existing.includes(MARK_START)) {
        process.stdout.write(`(no arch-graph block in ${p})\n`);
        return;
    }
    const stripped = stripMarkedSection(existing, MARK_START, MARK_END);

    // If the remaining file is just `#!/bin/sh` + comments, treat the hook as
    // effectively empty and remove it so we don't leave dead files.
    const meaningful = stripped
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l.length > 0 && !l.startsWith('#'))
        .join('');
    if (meaningful.length === 0) {
        const { unlink } = await import('node:fs/promises');
        await unlink(p);
        process.stdout.write(`✓ removed empty post-commit hook ${p}\n`);
        return;
    }

    await writeFile(p, stripped, 'utf8');
    process.stdout.write(`✓ removed arch-graph block from ${p}\n`);
}

export async function hookStatus(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const p = hookPath(args.repo);
    if (!existsSync(p)) {
        process.stdout.write(`status: not installed (no ${p})\n`);
        return;
    }
    const body = await readFile(p, 'utf8');
    if (!body.includes(MARK_START)) {
        process.stdout.write(`status: not installed (post-commit hook exists but has no arch-graph block)\n`);
        return;
    }
    const lines = body.split('\n').length;
    process.stdout.write(`status: installed at ${p} (${lines} lines total)\n`);
}
