// Git hook install/uninstall/status.
//
// Default mode: pre-commit — installs a shell block that validates the graph can
// be rebuilt before the commit. Generated graph artifacts are local build output
// and are intentionally not staged by the hook.
//
// Idempotent: re-running install replaces the block. If a hook already exists
// from another tool, our block is appended without disturbing it.
// Switching modes: the marker is stripped from the old file and written to the new.

import { existsSync } from 'node:fs';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { atomicWrite } from './atomic-write.js';
import { appendBlock, replaceMarkedSection, stripMarkedSection } from './marker-block.js';
import { registerProject } from './project-registry.js';

// Shell-comment markers for files that are sourced or executed as shell.
// Used in git hooks and SessionStart.sh.
export const MARK_START = '# >>> arch-graph >>>';
export const MARK_END = '# <<< arch-graph <<<';

// Markdown/HTML-comment markers for files where '#' would render as a heading
// (.cursorrules is treated as markdown by Cursor; CLAUDE.md is markdown).
// Keep them visually distinct from the shell markers above so a quick `grep`
// over a repo can answer "did arch-graph touch this file as text or as shell?"
export const CURSOR_MARK_START = '<!-- arch-graph:cursor -->';
export const CURSOR_MARK_END = '<!-- /arch-graph:cursor -->';

export function preCommitHookPath(repo: string): string {
    return resolve(repo, '.git', 'hooks', 'pre-commit');
}

export function postCommitHookPath(repo: string): string {
    return resolve(repo, '.git', 'hooks', 'post-commit');
}

// ---------------------------------------------------------------------------
// Hook body templates
// ---------------------------------------------------------------------------

function buildPreCommitBody(includeSemantic: boolean): string {
    void includeSemantic;

    return `${MARK_START}
# Validate arch-graph before commits that touch TypeScript files.
# Managed by \`arch-graph hook install\` — edit between markers will be overwritten.
if command -v arch-graph >/dev/null 2>&1; then
    if git diff --cached --name-only --diff-filter=ACMR 2>/dev/null | grep -qE '\\.ts$'; then
        # Real build errors (config parse, I/O) block the commit. Recall-floor
        # regressions are advisory by default and do not block — see \`arch-graph
        # build --strict\` for CI gating.
        arch-graph build --quiet || exit 1
    fi
fi
${MARK_END}
`;
}

function buildPostCommitBody(includeSemantic: boolean): string {
    const semanticBlock = includeSemantic ? `
        # Incremental semantic index update (default-on).
        arch-graph semantic build --quiet || true` : '';

    return `${MARK_START}
# Auto-rebuild arch-graph after commits that touch TypeScript files.
# Generated by \`arch-graph hook install --mode=post-commit\` — edit between markers will be
# overwritten on the next install. Remove with \`arch-graph hook uninstall\`.
if command -v arch-graph >/dev/null 2>&1; then
    # \`git diff-tree -r --no-commit-id --name-only HEAD\` works on the initial
    # commit too (HEAD~1 would not), and prints one path per line.
    if git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | grep -qE '\\.ts$'; then
        arch-graph build --quiet || true${semanticBlock}
    fi
fi
${MARK_END}
`;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type HookMode = 'pre-commit' | 'post-commit';

export interface HookArgs {
    repo: string; // path to repo root (we resolve .git/hooks/<hook> under it)
    mode: HookMode;
    /**
     * When true, the installed hook will NOT include the `arch-graph semantic build`
     * step — preserving the legacy structural-only hook behaviour.
     * Default: false (semantic build is included by default).
     */
    noIncludeSemantic?: boolean;
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export function parseHookArgs(argv: string[]): { sub: string; args: HookArgs } {
    const [sub, ...rest] = argv;
    let repo = '.';
    let mode: HookMode = 'pre-commit';
    let noIncludeSemantic = false;

    for (let i = 0; i < rest.length; i++) {
        const a = rest[i]!;
        if (a === '--repo' && rest[i + 1]) {
            repo = rest[++i]!;
        } else if (a.startsWith('--repo=')) {
            repo = a.slice('--repo='.length);
        } else if (a === '--mode' && rest[i + 1]) {
            mode = validateMode(rest[++i]!);
        } else if (a.startsWith('--mode=')) {
            mode = validateMode(a.slice('--mode='.length));
        } else if (a === '--no-include-semantic') {
            noIncludeSemantic = true;
        }
    }
    return { sub: sub ?? '', args: { repo: resolve(repo), mode, noIncludeSemantic } };
}

function validateMode(raw: string): HookMode {
    if (raw === 'pre-commit' || raw === 'post-commit') return raw;
    process.stderr.write(`error: --mode must be "pre-commit" or "post-commit", got "${raw}"\n`);
    process.exit(2);
}

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Install agent-side session hooks (e.g. .claude/hooks/SessionStart). */
export async function agentHookInstall(args: { repo: string; agent: 'claude' | 'cursor' | 'gemini' | 'all' }): Promise<void> {
    const repo = resolve(args.repo);
    
    if (args.agent === 'claude' || args.agent === 'all') {
        const hooksDir = resolve(repo, '.claude/hooks');
        await mkdir(hooksDir, { recursive: true });
        const startHookPath = resolve(hooksDir, 'SessionStart.sh');
        
        let existing = '';
        if (existsSync(startHookPath)) {
            existing = await readFile(startHookPath, 'utf8');
        }

        const body = `${MARK_START}
# Automatically orient the agent at the start of a session.
arch-graph code-intel summary --json
${MARK_END}
`;
        const next = existing.includes(MARK_START)
            ? replaceMarkedSection(existing, MARK_START, MARK_END, body)
            : existing.length === 0
                ? `#!/bin/sh\n${body}`
                : appendBlock(existing, body);

        await atomicWrite(startHookPath, next, 0o755);
        process.stdout.write(`✓ scaffolded .claude/hooks/SessionStart.sh\n`);
    }

    if (args.agent === 'cursor' || args.agent === 'all') {
        const cursorRulesPath = resolve(repo, '.cursorrules');

        let existing = '';
        if (existsSync(cursorRulesPath)) {
            existing = await readFile(cursorRulesPath, 'utf8');
        }

        // Use HTML-comment markers so the marker lines do not render as
        // visible content (or H1 headings) inside the rules file.
        const body = `${CURSOR_MARK_START}
## Architecture Orientation
Before starting work, always run:
arch-graph code-intel summary

Use surgical reads with exact line ranges from 'get_file_outline'.
${CURSOR_MARK_END}
`;
        const next = existing.includes(CURSOR_MARK_START)
            ? replaceMarkedSection(existing, CURSOR_MARK_START, CURSOR_MARK_END, body)
            : appendBlock(existing, body);

        await atomicWrite(cursorRulesPath, next);
        process.stdout.write(`✓ updated .cursorrules\n`);
    }
}

async function ensureGitRepo(repo: string): Promise<void> {
    if (!existsSync(resolve(repo, '.git'))) {
        throw new Error(`not a git repository: ${repo} (no .git directory)`);
    }
}

/**
 * Remove the arch-graph marker block from `filePath` if present.
 *
 * "Meaningful" classification: shell-style hook files (#!/bin/sh + #-comments)
 * are deleted when only those remain. Markdown files (.cursorrules, .md) are
 * left in place even if every remaining line starts with '#' — those are user
 * headings, not noise.
 */
async function removeMarkerFromFile(filePath: string): Promise<void> {
    if (!existsSync(filePath)) return;
    const body = await readFile(filePath, 'utf8');

    const hasShellMark = body.includes(MARK_START);
    const hasCursorMark = body.includes(CURSOR_MARK_START);
    if (!hasShellMark && !hasCursorMark) return;

    let stripped = body;
    if (hasShellMark) stripped = stripMarkedSection(stripped, MARK_START, MARK_END);
    if (hasCursorMark) stripped = stripMarkedSection(stripped, CURSOR_MARK_START, CURSOR_MARK_END);

    const isMarkdownLike = /\.cursorrules$|\.md$/i.test(filePath);
    const meaningful = stripped
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => {
            if (l.length === 0) return false;
            // In shell hooks, '#'-prefixed lines are comments → noise. In
            // markdown-like files they are headings → user content; keep.
            if (!isMarkdownLike && l.startsWith('#')) return false;
            return true;
        })
        .join('');
    if (meaningful.length === 0 && !isMarkdownLike) {
        const { unlink } = await import('node:fs/promises');
        await unlink(filePath);
    } else {
        await atomicWrite(filePath, stripped);
    }
}

/**
 * Write a hook block to `filePath`, replacing an existing arch-graph block
 * or appending to an existing third-party hook, or creating a fresh file.
 */
async function writeHookBlock(filePath: string, hookName: string, body: string): Promise<void> {
    await mkdir(dirname(filePath), { recursive: true });

    let existing = '';
    if (existsSync(filePath)) {
        existing = await readFile(filePath, 'utf8');
    }

    let next: string;
    if (existing.includes(MARK_START) && existing.includes(MARK_END)) {
        // Idempotent re-install: rewrite the block in place.
        next = replaceMarkedSection(existing, MARK_START, MARK_END, body);
    } else if (existing.length === 0) {
        next = `#!/bin/sh\n# git ${hookName} hook — managed by arch-graph (and possibly others)\n\n${body}`;
    } else {
        // Pre-existing hook from another tool — preserve it, append our block.
        next = appendBlock(existing, body);
        // Make sure the file still starts with a shebang.
        if (!next.startsWith('#!')) next = `#!/bin/sh\n${next}`;
    }

    await atomicWrite(filePath, next, 0o755);
    await chmod(filePath, 0o755);
}

// ---------------------------------------------------------------------------
// Public commands
// ---------------------------------------------------------------------------

export async function hookInstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    await registerProject(args.repo);

    const includeSemantic = !args.noIncludeSemantic;

    if (args.mode === 'pre-commit') {
        const target = preCommitHookPath(args.repo);
        const other = postCommitHookPath(args.repo);
        // Strip marker from the old mode's file when switching.
        await removeMarkerFromFile(other);
        await writeHookBlock(target, 'pre-commit', buildPreCommitBody(includeSemantic));
        process.stdout.write(`✓ pre-commit hook installed at ${target}\n`);
        process.stdout.write(`  Validates graph build before commits touching .ts files; generated artifacts stay local.\n`);
        process.stdout.write(`  Remove with: arch-graph hook uninstall\n`);
    } else {
        const target = postCommitHookPath(args.repo);
        const other = preCommitHookPath(args.repo);
        // Strip marker from the old mode's file when switching.
        await removeMarkerFromFile(other);
        await writeHookBlock(target, 'post-commit', buildPostCommitBody(includeSemantic));
        process.stdout.write(`✓ post-commit hook installed at ${target}\n`);
        process.stdout.write(`  Triggers \`arch-graph build --quiet\` after commits touching .ts files.\n`);
        if (includeSemantic) {
            process.stdout.write(`  Incremental semantic build included (use --no-include-semantic to skip).\n`);
        }
        process.stdout.write(`  Remove with: arch-graph hook uninstall\n`);
    }
}

export async function hookUninstall(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const pre = preCommitHookPath(args.repo);
    const post = postCommitHookPath(args.repo);

    let removed = 0;

    for (const [label, p] of [['pre-commit', pre], ['post-commit', post]] as [string, string][]) {
        if (!existsSync(p)) continue;
        const body = await readFile(p, 'utf8');
        if (!body.includes(MARK_START)) continue;

        const stripped = stripMarkedSection(body, MARK_START, MARK_END);
        const meaningful = stripped
            .split('\n')
            .map((l) => l.trim())
            .filter((l) => l.length > 0 && !l.startsWith('#'))
            .join('');
        if (meaningful.length === 0) {
            const { unlink } = await import('node:fs/promises');
            await unlink(p);
            process.stdout.write(`✓ removed empty ${label} hook ${p}\n`);
        } else {
            await atomicWrite(p, stripped);
            process.stdout.write(`✓ removed arch-graph block from ${p}\n`);
        }
        removed++;
    }

    if (removed === 0) {
        process.stdout.write(`(no arch-graph block found in pre-commit or post-commit hooks)\n`);
    }
}

export async function hookStatus(args: HookArgs): Promise<void> {
    await ensureGitRepo(args.repo);
    const pre = preCommitHookPath(args.repo);
    const post = postCommitHookPath(args.repo);

    let found = false;

    if (existsSync(pre)) {
        const body = await readFile(pre, 'utf8');
        if (body.includes(MARK_START)) {
            const lines = body.split('\n').length;
            process.stdout.write(`status: installed (mode=pre-commit) at ${pre} (${lines} lines total)\n`);
            found = true;
        }
    }

    if (existsSync(post)) {
        const body = await readFile(post, 'utf8');
        if (body.includes(MARK_START)) {
            const lines = body.split('\n').length;
            process.stdout.write(`status: installed (mode=post-commit) at ${post} (${lines} lines total)\n`);
            found = true;
        }
    }

    if (!found) {
        process.stdout.write(`status: not installed (no arch-graph block in pre-commit or post-commit hooks)\n`);
    }
}
